# Generated by Django 4.0.2 on 2022-02-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
